// lib/geo.ts
export const COUNTRIES = [
  // South Asia
  "Bangladesh",
  "India",
  "Pakistan",
  "Sri Lanka",
  "Nepal",

  // East & Southeast Asia
  "China",
  "Japan",
  "South Korea",
  "Indonesia",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Singapore",

  // Middle East
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Israel",
  "Turkey",

  // Africa
  "South Africa",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Morocco",
  "Ghana",
  "Ethiopia",
  "Tunisia",

  // Europe (West/North/Central/East)
  "United Kingdom",
  "Ireland",
  "France",
  "Germany",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Italy",
  "Spain",
  "Portugal",
  "Greece",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czechia",
  "Hungary",
  "Romania",
  "Ukraine",

  // Americas
  "United States",
  "Canada",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "New Zealand",
  "Australia",
] as const;

export type Country = (typeof COUNTRIES)[number];

export const STATES_BY_COUNTRY: Record<string, string[]> = {
  // --- South Asia ---
  Bangladesh: [
    "Dhaka",
    "Chattogram",
    "Rajshahi",
    "Khulna",
    "Sylhet",
    "Barishal",
    "Rangpur",
    "Mymensingh",
  ],
  India: [
    "Maharashtra",
    "Uttar Pradesh",
    "Delhi",
    "Karnataka",
    "Tamil Nadu",
    "Gujarat",
    "Telangana",
    "West Bengal",
    "Rajasthan",
    "Kerala",
  ],
  Pakistan: [
    "Punjab",
    "Sindh",
    "Khyber Pakhtunkhwa",
    "Balochistan",
    "Islamabad Capital Territory",
  ],
  "Sri Lanka": [
    "Western",
    "Central",
    "Southern",
    "Northern",
    "Eastern",
    "North Western",
    "North Central",
    "Uva",
    "Sabaragamuwa",
  ],
  Nepal: [
    "Bagmati",
    "Gandaki",
    "Koshi",
    "Madhesh",
    "Lumbini",
    "Karnali",
    "Sudurpashchim",
  ],

  // --- East & Southeast Asia ---
  China: [
    "Beijing",
    "Shanghai",
    "Guangdong",
    "Zhejiang",
    "Jiangsu",
    "Sichuan",
    "Shandong",
    "Hubei",
    "Henan",
    "Fujian",
  ],
  Japan: [
    "Tokyo",
    "Osaka",
    "Kanagawa",
    "Aichi",
    "Hokkaidō",
    "Fukuoka",
    "Hyōgo",
    "Kyōto",
    "Saitama",
    "Chiba",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Gyeonggi",
    "Gyeongsangnam-do",
    "Jeollanam-do",
    "Chungcheongnam-do",
    "Gangwon",
    "Jeju",
  ],
  Indonesia: [
    "DKI Jakarta",
    "West Java",
    "Central Java",
    "East Java",
    "Bali",
    "Yogyakarta",
    "West Sumatra",
    "North Sumatra",
    "South Sulawesi",
    "Riau",
  ],
  Malaysia: [
    "Selangor",
    "Kuala Lumpur",
    "Johor",
    "Penang",
    "Perak",
    "Sabah",
    "Sarawak",
    "Negeri Sembilan",
    "Pahang",
    "Kedah",
  ],
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Chonburi",
    "Phuket",
    "Nakhon Ratchasima",
    "Nakhon Si Thammarat",
    "Khon Kaen",
    "Surat Thani",
  ],
  Vietnam: [
    "Hanoi",
    "Ho Chi Minh City",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Binh Duong",
    "Dong Nai",
    "Quang Ninh",
  ],
  Philippines: [
    "Metro Manila",
    "Cebu",
    "Davao del Sur",
    "Rizal",
    "Cavite",
    "Laguna",
    "Batangas",
    "Pampanga",
    "Bulacan",
  ],
  Singapore: ["—"],

  // --- Middle East ---
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Ajman",
    "Umm Al Quwain",
    "Ras Al Khaimah",
    "Fujairah",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Makkah",
    "Madinah",
    "Eastern Province",
    "Asir",
    "Tabuk",
    "Qassim",
    "Jazan",
    "Najran",
  ],
  Qatar: [
    "Doha",
    "Al Rayyan",
    "Al Wakrah",
    "Umm Salal",
    "Al Khor",
    "Al Daayen",
  ],
  Kuwait: [
    "Al Asimah",
    "Hawalli",
    "Farwaniya",
    "Ahmadi",
    "Jahra",
    "Mubarak Al-Kabeer",
  ],
  Israel: [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Central District",
    "Northern District",
    "Southern District",
  ],
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Adana",
    "Konya",
    "Gaziantep",
    "Kocaeli",
    "Mersin",
  ],

  // --- Africa ---
  "South Africa": [
    "Gauteng",
    "Western Cape",
    "KwaZulu-Natal",
    "Eastern Cape",
    "Mpumalanga",
    "Limpopo",
    "North West",
    "Free State",
    "Northern Cape",
  ],
  Egypt: [
    "Cairo",
    "Giza",
    "Alexandria",
    "Dakahlia",
    "Sharqia",
    "Gharbia",
    "Monufia",
    "Qalyubia",
    "Luxor",
    "Aswan",
  ],
  Nigeria: [
    "Lagos",
    "FCT Abuja",
    "Kano",
    "Rivers",
    "Oyo",
    "Kaduna",
    "Anambra",
    "Delta",
    "Edo",
    "Ogun",
  ],
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Kiambu",
    "Nakuru",
    "Kisumu",
    "Uasin Gishu",
    "Machakos",
  ],
  Morocco: [
    "Casablanca-Settat",
    "Rabat-Salé-Kénitra",
    "Marrakech-Safi",
    "Fès-Meknès",
    "Souss-Massa",
    "Tanger-Tétouan-Al Hoceïma",
  ],
  Ghana: [
    "Greater Accra",
    "Ashanti",
    "Northern",
    "Eastern",
    "Western",
    "Central",
    "Volta",
  ],
  Ethiopia: ["Addis Ababa", "Oromia", "Amhara", "Tigray", "Sidama", "SNNPR"],
  Tunisia: [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Nabeul",
    "Monastir",
    "Gabès",
  ],

  // --- Europe ---
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  Ireland: [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Kildare",
    "Meath",
  ],
  France: [
    "Île-de-France",
    "Auvergne-Rhône-Alpes",
    "Provence-Alpes-Côte d'Azur",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Hauts-de-France",
    "Grand Est",
    "Bretagne",
  ],
  Germany: [
    "Bavaria",
    "Baden-Württemberg",
    "North Rhine-Westphalia",
    "Hesse",
    "Lower Saxony",
    "Berlin",
    "Hamburg",
    "Saxony",
  ],
  Netherlands: [
    "North Holland",
    "South Holland",
    "Utrecht",
    "North Brabant",
    "Gelderland",
    "Overijssel",
  ],
  Belgium: ["Flanders", "Wallonia", "Brussels-Capital Region"],
  Switzerland: [
    "Zürich",
    "Bern",
    "Vaud",
    "Geneva",
    "Aargau",
    "St. Gallen",
    "Basel-Stadt",
  ],
  Austria: [
    "Vienna",
    "Lower Austria",
    "Upper Austria",
    "Styria",
    "Tyrol",
    "Salzburg",
    "Carinthia",
  ],
  Italy: [
    "Lombardy",
    "Lazio",
    "Campania",
    "Veneto",
    "Emilia-Romagna",
    "Piedmont",
    "Tuscany",
    "Sicily",
  ],
  Spain: [
    "Madrid",
    "Catalonia",
    "Andalusia",
    "Valencian Community",
    "Basque Country",
    "Galicia",
    "Castile and León",
    "Balearic Islands",
  ],
  Portugal: ["Lisbon", "Porto", "Braga", "Setúbal", "Aveiro", "Faro"],
  Greece: [
    "Attica",
    "Central Macedonia",
    "Thessaly",
    "Crete",
    "Western Greece",
    "Peloponnese",
  ],
  Sweden: ["Stockholm", "Västra Götaland", "Skåne", "Uppsala", "Östergötland"],
  Norway: ["Oslo", "Viken", "Vestland", "Trøndelag", "Rogaland", "Agder"],
  Denmark: [
    "Capital Region",
    "Central Jutland",
    "Southern Denmark",
    "Zealand",
    "North Jutland",
  ],
  Finland: [
    "Uusimaa",
    "Pirkanmaa",
    "Southwest Finland",
    "North Ostrobothnia",
    "Satakunta",
  ],
  Poland: [
    "Masovian",
    "Lesser Poland",
    "Silesian",
    "Pomeranian",
    "Greater Poland",
    "Lower Silesian",
  ],
  Czechia: [
    "Prague",
    "Central Bohemian",
    "South Moravian",
    "Moravian-Silesian",
    "Plzeň",
  ],
  Hungary: [
    "Budapest",
    "Pest",
    "Borsod-Abaúj-Zemplén",
    "Győr-Moson-Sopron",
    "Csongrád-Csanád",
  ],
  Romania: ["Bucharest", "Cluj", "Timiș", "Iași", "Constanța", "Brașov"],
  Ukraine: ["Kyiv", "Lviv", "Kharkiv", "Dnipropetrovsk", "Odesa"],

  // --- Americas & Oceania ---
  "United States": [
    "California",
    "New York",
    "Texas",
    "Florida",
    "Illinois",
    "Pennsylvania",
    "Ohio",
    "Georgia",
    "North Carolina",
    "Washington",
  ],
  Canada: [
    "Ontario",
    "Quebec",
    "British Columbia",
    "Alberta",
    "Manitoba",
    "Saskatchewan",
    "Nova Scotia",
    "New Brunswick",
  ],
  Mexico: [
    "Ciudad de México",
    "Jalisco",
    "Nuevo León",
    "Estado de México",
    "Puebla",
    "Guanajuato",
    "Baja California",
    "Yucatán",
    "Quintana Roo",
  ],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Minas Gerais",
    "Bahia",
    "Paraná",
    "Rio Grande do Sul",
    "Pernambuco",
    "Ceará",
    "Santa Catarina",
    "Distrito Federal",
  ],
  Argentina: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán"],
  Chile: [
    "Santiago Metropolitan",
    "Valparaíso",
    "Biobío",
    "Maule",
    "Araucanía",
  ],
  Colombia: [
    "Bogotá D.C.",
    "Antioquia",
    "Valle del Cauca",
    "Atlántico",
    "Santander",
  ],
  Peru: ["Lima", "Arequipa", "La Libertad", "Piura", "Cusco"],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Canterbury",
    "Waikato",
    "Otago",
    "Bay of Plenty",
  ],
  Australia: [
    "New South Wales",
    "Victoria",
    "Queensland",
    "Western Australia",
    "South Australia",
    "Tasmania",
    "Northern Territory",
    "Australian Capital Territory",
  ],
};

export const getStates = (country?: string) =>
  (country && STATES_BY_COUNTRY[country]) || [];
