// lib/geo.ts
// United States is placed first as most users are expected to be from the US
export const COUNTRIES = [
  "United States",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Aruba",
  "Australia",
  "Austria",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Belize",
  "Bermuda",
  "Bonaire",
  "Brazil",
  "British Virgin Islands",
  "Cambodia",
  "Canada",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Czechia",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "England",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "France (Mayotte)",
  "Germany",
  "Ghana",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe (France)",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Madagascar",
  "Malaysia",
  "Maldives",
  "Marshall Islands",
  "Martinique (France)",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia (France)",
  "New Zealand",
  "Nigeria",
  "Northern Ireland",
  "Norway",
  "Pakistan",
  "Palau",
  "Panama",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Réunion (France)",
  "Saint Barthélemy (France)",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and Grenadines",
  "Samoa",
  "Saudi Arabia",
  "Scotland",
  "Seychelles",
  "Singapore",
  "Solomon Islands",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "São Tomé & Príncipe",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turks and Caicos",
  "Tuvalu",
  "UK Overseas Territory",
  "Ukraine",
  "United Arab Emirates",
  "United States (USVI)",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Yemen",
  "Others",
] as const;

export type Country = (typeof COUNTRIES)[number];

export const STATES_BY_COUNTRY: Record<string, string[]> = {
  // --- South Asia ---
  Bangladesh: [
    "Dhaka",
    "Chattogram",
    "Rajshahi",
    "Khulna",
    "Sylhet",
    "Barishal",
    "Rangpur",
    "Mymensingh",
  ],
  India: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi (National Capital Territory)",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
    // Additional islands/regions
    "Agatti",
    "Amini",
    "Andrott",
    "Bharatpur",
    "Bitra",
    "Car Nicobar",
    "Chetlat",
    "Govind Nagar",
    "Great Nicobar",
    "Havelock (Swaraj)",
    "Havelock Island",
    "Kadmat",
    "Kalpeni",
    "Katchal",
    "Kavaratti",
    "Kiltan",
    "Little Andaman",
    "Middle Andaman",
    "Minicoy",
    "Nancowry",
    "Neil (Shaheed)",
    "North Andaman",
    "South Andaman",
  ],

  Pakistan: [
    "Balochistan",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
    "Islamabad Capital Territory",
    "Azad Jammu and Kashmir",
    "Gilgit-Baltistan",
  ],

  "Sri Lanka": [
    "Central",
    "Eastern",
    "Northern",
    "North Central",
    "North Western",
    "Sabaragamuwa",
    "Southern",
    "Uva",
    "Western",
    // Additional islands/regions
    "Delft Island",
    "Delft Town",
    "Sri Lanka",
  ],

  Nepal: [
    "Koshi Province",
    "Madhesh Province",
    "Bagmati Province",
    "Gandaki Province",
    "Lumbini Province",
    "Karnali Province",
    "Sudurpashchim Province",
  ],

  // --- East & Southeast Asia ---
  China: [
    // Municipalities (直辖市)
    "Beijing",
    "Shanghai",
    "Tianjin",
    "Chongqing",

    // Provinces (省)
    "Anhui",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanxi",
    "Sichuan",
    "Yunnan",
    "Zhejiang",

    // Autonomous regions (自治区)
    "Guangxi Zhuang",
    "Inner Mongolia",
    "Ningxia Hui",
    "Tibet (Xizang)",
    "Xinjiang Uyghur",

    // Special administrative regions (特别行政区)
    "Hong Kong",
    "Macau",

    // Additional regions/islands
    "Daishan Island",
    "Gulangyu (Fujian)",
    "Haikou",
    "Hainan Island",
    "Jintang Island",
    "Liuheng Island",
    "Pingtan (Fujian)",
    "Sanya",
    "Taohua Island",
    "Xiushan Island",
    "Yongxing Island (Xisha)",
    "Zhoushan Island",
    "Zhujiajian Island",
  ],

  Japan: [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaidō",
    "Hyōgo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kōchi",
    "Kumamoto",
    "Kyōto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Ōita",
    "Okayama",
    "Okinawa",
    "Ōsaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
    // Additional islands/regions
    "Hokkaido",
    "Honshu",
    "Kyushu",
    "Miyanoura",
    "Motomachi",
    "Naha",
    "Shikoku",
  ],

  "South Korea": [
    "Seoul",
    "Busan",
    "Daegu",
    "Incheon",
    "Gwangju",
    "Daejeon",
    "Ulsan",
    "Sejong",
    "Gyeonggi-do",
    "Gangwon-do",
    "Chungcheongbuk-do",
    "Chungcheongnam-do",
    "Jeollabuk-do",
    "Jeollanam-do",
    "Gyeongsangbuk-do",
    "Gyeongsangnam-do",
    "Jeju-do",
    // Additional regions
    "Jeju",
    "Jeju City",
    "Seogwipo",
  ],

  Indonesia: [
    "Aceh",
    "North Sumatra",
    "West Sumatra",
    "Riau",
    "Riau Islands",
    "Jambi",
    "Bengkulu",
    "South Sumatra",
    "Bangka Belitung Islands",
    "Lampung",
    "Banten",
    "West Java",
    "Central Java",
    "DI Yogyakarta",
    "East Java",
    "Bali",
    "West Kalimantan",
    "Central Kalimantan",
    "South Kalimantan",
    "East Kalimantan",
    "North Kalimantan",
    "North Sulawesi",
    "Central Sulawesi",
    "South Sulawesi",
    "Southeast Sulawesi",
    "Gorontalo",
    "West Sulawesi",
    "Maluku",
    "North Maluku",
    "West Nusa Tenggara",
    "East Nusa Tenggara",
    "West Papua",
    "South Papua",
    "Central Papua",
    "Highland Papua",
    "Papua",
    // Additional islands/regions
    "Denpasar",
    "Flores",
    "Java",
    "Kalimantan",
    "Labuan Bajo",
    "Loh Liang",
    "Lombok",
    "Mataram",
    "Seminyak",
    "Sulawesi",
    "Sumatra",
    "Sumbawa",
    "Ubud",
  ],

  Malaysia: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Melaka",
    "Negeri Sembilan",
    "Pahang",
    "Penang (Pulau Pinang)",
    "Perak",
    "Perlis",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
    "Kuala Lumpur",
    "Labuan",
    "Putrajaya",
    // Additional islands/regions
    "Borneo",
    "George Town",
    "Kampung Tekek",
    "Kapas Island",
    "Kuah",
    "Langkawi",
    "Penang Island",
    "Perhentian Besar",
    "Perhentian Kecil",
    "Redang Island",
    "Tenggol Island",
    "Tioman Island",
  ],

  Thailand: [
    "Amnat Charoen",
    "Ang Thong",
    "Bangkok",
    "Bueng Kan",
    "Buri Ram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phang Nga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phrae",
    "Phuket",
    "Prachinburi",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
    // Additional islands/regions
    "Chaweng",
    "Koh Chang",
    "Koh Kood",
    "Koh Lanta",
    "Koh Mak",
    "Koh Phangan",
    "Koh Phi Phi",
    "Koh Samet",
    "Koh Samui",
    "Koh Tao",
    "Koh Yao Noi",
    "Mae Haad",
    "Patong",
    "Tonsai Village",
  ],

  Vietnam: [
    "An Giang",
    "Bà Rịa–Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Dương",
    "Bình Định",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên–Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Ho Chi Minh City (Thành phố Hồ Chí Minh)",
    // Additional islands/regions
    "Bạch Long Vĩ Island",
    "Cát Bà Island",
    "Côn Đảo Islands",
    "Cù Lao Chàm",
    "Duong Dong",
    "Hòn Sơn Island",
    "Hòn Tre Island",
    "Lý Sơn Island",
    "Nam Du Islands",
    "Phú Quốc",
    "Quang Ninh",
  ],

  Philippines: [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Basilan",
    "Bataan",
    "Batanes",
    "Batangas",
    "Benguet",
    "Biliran",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Cotabato",
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Dinagat Islands",
    "Eastern Samar",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Leyte",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Marinduque",
    "Masbate",
    "Metro Manila (National Capital Region)",
    "Misamis Occidental",
    "Misamis Oriental",
    "Mountain Province",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "Samar (Western Samar)",
    "Sarangani",
    "Siquijor",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
    // Additional islands/regions
    "Calayan Island",
    "Camiguin Island",
    "Cebu City",
    "Coron",
    "Culion Island",
    "Cuyo Island",
    "El Nido",
    "General Luna",
    "Guimaras Island",
    "Luzon",
    "Malay",
    "Mindanao",
    "Mindoro",
    "Negros",
    "Panay",
    "Puerto Princesa",
    "Romblon Island",
    "Samar",
    "Siargao",
    "Siargao Island",
    "Tagbilaran",
    "Ticao Island",
  ],

  Singapore: [
    "Central Region",
    "East Region",
    "North Region",
    "North-East Region",
    "West Region",
  ],

  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain",
  ],

  "Saudi Arabia": [
    "Riyadh",
    "Makkah",
    "Madinah",
    "Eastern Province (Ash Sharqiyah)",
    "Asir",
    "Tabuk",
    "Hail",
    "Northern Borders (Al Hudud ash Shamaliyah)",
    "Jazan",
    "Najran",
    "Al Bahah",
    "Al Jawf",
    "Qassim",
  ],

  Qatar: [
    "Al Shamal",
    "Al Khor",
    "Al Daayen",
    "Umm Salal",
    "Al Rayyan",
    "Doha",
    "Al Wakrah",
    "Al Shahaniya",
  ],

  Kuwait: [
    "Al Asimah (Capital)",
    "Hawalli",
    "Farwaniya",
    "Ahmadi",
    "Jahra",
    "Mubarak Al-Kabeer",
  ],

  Israel: [
    "Jerusalem District",
    "Tel Aviv District",
    "Central District",
    "Haifa District",
    "Northern District",
    "Southern District",
  ],
  Turkey: [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Mersin",
    "Istanbul",
    "İzmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Kahramanmaraş",
    "Mardin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "Kırıkkale",
    "Batman",
    "Şırnak",
    "Bartın",
    "Ardahan",
    "Iğdır",
    "Yalova",
    "Karabük",
    "Kilis",
    "Osmaniye",
    "Düzce",
  ],

  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Northern Cape",
    "North West",
    "Western Cape",
  ],

  Egypt: [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley (El Wadi El Gedid)",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
  ],

  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
    "Federal Capital Territory (Abuja)",
  ],

  Kenya: [
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Elgeyo-Marakwet",
    "Embu",
    "Garissa",
    "Homa Bay",
    "Isiolo",
    "Kajiado",
    "Kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang’a",
    "Nairobi",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Samburu",
    "Siaya",
    "Taita-Taveta",
    "Tana River",
    "Tharaka-Nithi",
    "Trans Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir",
    "West Pokot",
  ],

  Morocco: [
    "Tanger-Tétouan-Al Hoceïma",
    "L’Oriental",
    "Fès-Meknès",
    "Rabat-Salé-Kénitra",
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Marrakech-Safi",
    "Drâa-Tafilalet",
    "Souss-Massa",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Dakhla-Oued Ed-Dahab",
  ],

  Ghana: [
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono East",
    "Central",
    "Eastern",
    "Greater Accra",
    "Northern",
    "North East",
    "Oti",
    "Savannah",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Western North",
  ],

  Ethiopia: [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Central Ethiopia Region",
    "Dire Dawa",
    "Gambela",
    "Harari",
    "Oromia",
    "Sidama",
    "South Ethiopia Regional State",
    "South West Ethiopia Peoples’ Region",
    "Somali",
    "Tigray",
  ],

  Tunisia: [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
  ],

  England: [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "City of London",
    "Cornwall",
    "County Durham",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "East Riding of Yorkshire",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
  ],

  Scotland: [
    "Aberdeen City",
    "Aberdeenshire",
    "Angus",
    "Argyll and Bute",
    "Clackmannanshire",
    "Dumfries and Galloway",
    "Dundee City",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "Edinburgh (City of)",
    "Falkirk",
    "Fife",
    "Glasgow City",
    "Highland",
    "Inverclyde",
    "Midlothian",
    "Moray",
    "Na h-Eileanan Siar (Western Isles)",
    "North Ayrshire",
    "North Lanarkshire",
    "Orkney Islands",
    "Perth and Kinross",
    "Renfrewshire",
    "Scottish Borders",
    "Shetland Islands",
    "South Ayrshire",
    "South Lanarkshire",
    "Stirling",
    "West Dunbartonshire",
    "West Lothian",
    // Additional islands
    "Eday",
    "Hoy",
    "Isle of Arran",
    "Isle of Barra",
    "Isle of Bute",
    "Isle of Colonsay",
    "Isle of Eigg",
    "Isle of Gigha",
    "Isle of Great Cumbrae",
    "Isle of Iona",
    "Isle of Islay",
    "Isle of Jura",
    "Isle of Lewis",
    "Isle of Mull",
    "Isle of Skye",
    "Isle of Tiree",
    "Mainland (Orkney)",
    "North Ronaldsay",
    "Papa Westray",
    "Rousay",
    "Sanday",
    "Shapinsay",
    "Shetland Mainland",
    "South Ronaldsay",
    "Stronsay",
    "Westray",
  ],

  Wales: [
    "Anglesey (Isle of)",
    "Blaenau Gwent",
    "Bridgend",
    "Caerphilly",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Conwy",
    "Denbighshire",
    "Flintshire",
    "Gwynedd",
    "Merthyr Tydfil",
    "Monmouthshire",
    "Neath Port Talbot",
    "Newport",
    "Pembrokeshire",
    "Powys",
    "Rhondda Cynon Taf",
    "Swansea",
    "Torfaen",
    "Vale of Glamorgan",
    "Wrexham",
  ],

  "Northern Ireland": [
    "Antrim and Newtownabbey",
    "Ards and North Down",
    "Armagh City, Banbridge and Craigavon",
    "Belfast",
    "Causeway Coast and Glens",
    "Derry City and Strabane",
    "Fermanagh and Omagh",
    "Lisburn and Castlereagh",
    "Mid and East Antrim",
    "Mid Ulster",
    "Newry, Mourne and Down",
  ],
  Ireland: [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
  ],

  France: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
    "Guadeloupe",
    "Martinique",
    "Guyane (French Guiana)",
    "La Réunion",
    "Mayotte",
    // Additional regions
    "Corsica",
    "Grande-Terre",
    "Le Bourg",
    "Porquerolles",
  ],

  Germany: [
    "Baden-Württemberg",
    "Bavaria (Bayern)",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse (Hessen)",
    "Lower Saxony (Niedersachsen)",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia (Nordrhein-Westfalen)",
    "Rhineland-Palatinate (Rheinland-Pfalz)",
    "Saarland",
    "Saxony (Sachsen)",
    "Saxony-Anhalt (Sachsen-Anhalt)",
    "Schleswig-Holstein",
    "Thuringia (Thüringen)",
  ],

  Netherlands: [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
  ],

  Belgium: ["Flanders", "Wallonia", "Brussels-Capital Region"],

  Switzerland: [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Graubünden",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Vaud",
    "Valais",
    "Zug",
    "Zürich",
  ],

  Austria: [
    "Burgenland",
    "Carinthia (Kärnten)",
    "Lower Austria (Niederösterreich)",
    "Upper Austria (Oberösterreich)",
    "Salzburg",
    "Styria (Steiermark)",
    "Tyrol (Tirol)",
    "Vorarlberg",
    "Vienna (Wien)",
  ],

  Italy: [
    "Abruzzo",
    "Aosta Valley",
    "Apulia (Puglia)",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Trentino-Alto Adige/Südtirol",
    "Tuscany",
    "Umbria",
    "Veneto",
    // Additional islands
    "Capri",
    "Capri Town",
    "Ischia",
    "Ischia Porto",
    "Lampedusa",
    "Lipari",
    "Panarea",
    "Procida",
    "Procida Town",
    "Stromboli",
  ],

  Spain: [
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country (Euskadi)",
    "Canary Islands",
    "Cantabria",
    "Castile and León",
    "Castile-La Mancha",
    "Catalonia",
    "Extremadura",
    "Galicia",
    "Madrid",
    "Murcia",
    "Navarre (Navarra)",
    "La Rioja",
    "Valencian Community (Comunitat Valenciana)",
    // Additional islands
    "Formentera",
    "Ibiza",
    "Lanzarote",
    "Mahón",
    "Mallorca",
    "Minorca",
    "Puerto del Rosario",
    "Santa Cruz de la Palma",
    "Tenerife",
  ],

  Portugal: [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisbon (Lisboa)",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Azores (Açores)",
    "Madeira",
    // Additional islands/regions
    "Angra do Heroísmo",
    "Pico",
    "São Miguel",
  ],

  Greece: [
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "Eastern Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "Western Greece",
    "Western Macedonia",
    // Additional regions/islands
    "Argostoli",
    "Chania",
    "Corfu",
    "Corfu Town",
    "Heraklion",
    "Kefalonia",
    "Kos",
    "Lesbos",
    "Mykonos",
    "Naxos",
    "Paros",
    "Rhodes",
    "Samos",
    "Santorini",
    "Skiathos",
    "Tinos",
    "Zakynthos",
    "Zakynthos Town",
  ],

  Sweden: [
    "Blekinge",
    "Dalarna",
    "Gävleborg",
    "Gotland",
    "Halland",
    "Jämtland",
    "Jönköping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Örebro",
    "Östergötland",
    "Skåne",
    "Södermanland",
    "Stockholm",
    "Uppsala",
    "Värmland",
    "Västerbotten",
    "Västernorrland",
    "Västmanland",
    "Västra Götaland",
  ],

  Norway: [
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Troms og Finnmark",
    "Trøndelag",
    "Vestfold og Telemark",
    "Vestland",
    "Viken",
    // Additional regions
    "Longyearbyen",
  ],

  Denmark: [
    "Capital Region (Hovedstaden)",
    "Central Jutland (Midtjylland)",
    "North Jutland (Nordjylland)",
    "Zealand (Sjælland)",
    "Southern Denmark (Syddanmark)",
    // Additional regions
    "Faroe Islands",
  ],

  Finland: [
    "Uusimaa",
    "Southwest Finland (Varsinais-Suomi)",
    "Satakunta",
    "Kanta-Häme",
    "Pirkanmaa",
    "Päijät-Häme",
    "Kymenlaakso",
    "South Karelia",
    "South Savo",
    "North Savo",
    "North Karelia",
    "Central Finland",
    "South Ostrobothnia",
    "Ostrobothnia",
    "Central Ostrobothnia",
    "North Ostrobothnia",
    "Kainuu",
    "Lapland",
    "Åland Islands",
  ],

  Poland: [
    "Lower Silesian (Dolnośląskie)",
    "Kuyavian-Pomeranian (Kujawsko-Pomorskie)",
    "Lublin (Lubelskie)",
    "Lubusz (Lubuskie)",
    "Łódź (Łódzkie)",
    "Lesser Poland (Małopolskie)",
    "Masovian (Mazowieckie)",
    "Opole (Opolskie)",
    "Podlaskie",
    "Pomeranian (Pomorskie)",
    "Silesian (Śląskie)",
    "Subcarpathian (Podkarpackie)",
    "Świętokrzyskie",
    "Warmian-Masurian (Warmińsko-Mazurskie)",
    "Greater Poland (Wielkopolskie)",
    "West Pomeranian (Zachodniopomorskie)",
  ],

  Czechia: [
    "Central Bohemian",
    "Hradec Králové",
    "Karlovy Vary",
    "Liberec",
    "Moravian-Silesian",
    "Olomouc",
    "Pardubice",
    "Plzeň",
    "Prague",
    "South Bohemian",
    "South Moravian",
    "Ústí nad Labem",
    "Vysočina",
    "Zlín",
  ],

  Hungary: [
    "Bács-Kiskun",
    "Baranya",
    "Békés",
    "Borsod-Abaúj-Zemplén",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala",
    "Budapest",
  ],

  Romania: [
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brăila",
    "Brașov",
    "Bucharest",
    "Buzău",
    "Călărași",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Sălaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vâlcea",
    "Vaslui",
    "Vrancea",
  ],

  Ukraine: [
    "Cherkasy",
    "Chernihiv",
    "Chernivtsi",
    "Dnipropetrovsk",
    "Donetsk",
    "Ivano-Frankivsk",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyi",
    "Kyiv",
    "Kirovohrad",
    "Luhansk",
    "Lviv",
    "Mykolaiv",
    "Odesa",
    "Poltava",
    "Rivne",
    "Sumy",
    "Ternopil",
    "Vinnytsia",
    "Volyn",
    "Zakarpattia",
    "Zaporizhzhia",
    "Zhytomyr",
    "Sevastopol",
    "Autonomous Republic of Crimea",
  ],

  // --- Americas & Oceania ---
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],

  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
    // Additional regions
    "Iqaluit",
    "Vancouver Island",
  ],

  Mexico: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Mexico City (Ciudad de México)",
    "Mexico State (Estado de México)",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
    // Additional islands
    "Cozumel",
    "Isla Mujeres",
  ],

  Brazil: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    // Additional regions
    "Brazil",
    "Fernando de Noronha",
    "Ilha Comprida",
  ],

  Argentina: [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego, Antártida e Islas del Atlántico Sur",
    "Tucumán",
  ],

  Chile: [
    "Arica y Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Santiago Metropolitan (Región Metropolitana de Santiago)",
    "Libertador General Bernardo O'Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "La Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén del General Carlos Ibáñez del Campo",
    "Magallanes y de la Antártica Chilena",
    // Additional regions
    "Chile",
  ],

  Colombia: [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Córdoba",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada",
    "Bogotá D.C.",
    // Additional regions
    "Providencia",
    "Providencia Island",
    "San Andrés",
    "Tierra Bomba Island",
  ],

  Peru: [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali",
  ],

  "New Zealand": [
    "Northland",
    "Auckland",
    "Waikato",
    "Bay of Plenty",
    "Gisborne",
    "Hawke’s Bay",
    "Taranaki",
    "Manawatū-Whanganui",
    "Wellington",
    "Tasman",
    "Nelson",
    "Marlborough",
    "West Coast",
    "Canterbury",
    "Otago",
    "Southland",
  ],

  Australia: [
    "New South Wales",
    "Victoria",
    "Queensland",
    "Western Australia",
    "South Australia",
    "Tasmania",
    "Northern Territory",
    "Australian Capital Territory",
  ],

  // --- New Countries from JSON ---
  Anguilla: ["Anguilla"],

  Antarctica: [
    "Base Presidente Eduardo Frei",
    "Grytviken",
    "King George Island",
    "Macquarie Base",
    "McMurdo Station",
    "Spanish Base",
  ],

  "Antigua and Barbuda": ["Antigua", "Barbuda"],

  Aruba: ["Aruba"],

  Bahamas: [
    "Abaco Island",
    "Acklins Island",
    "Andros Island",
    "Bimini",
    "Cat Island",
    "Crooked Island",
    "Eleuthera",
    "Grand Bahama",
    "Great Exuma",
    "Great Inagua",
    "Long Island",
    "Mayaguana",
    "New Providence",
    "Paradise Island",
    "Ragged Island",
  ],

  Barbados: ["Barbados"],

  Belize: ["Ambergris Caye", "Caye Caulker"],

  Bermuda: [
    "Bermuda",
    "Devonshire Parish",
    "Hamilton Parish",
    "Paget Parish",
    "Pembroke Parish",
    "Sandys Parish",
    "Smith's Parish",
    "Southampton Parish",
    "St. George's Parish",
    "Warwick Parish",
  ],

  Bonaire: ["Bonaire"],

  "British Virgin Islands": [
    "Anegada",
    "Cooper Island",
    "Jost Van Dyke",
    "Norman Island",
    "Peter Island",
    "Tortola",
    "Virgin Gorda",
  ],

  Cambodia: [
    "Koh Rong",
    "Koh Rong Sanloem",
    "Koh Sdach",
    "Koh Ta Kiev",
    "Koh Thmei",
    "Koh Tonsay (Rabbit)",
  ],

  "Cayman Islands": ["Cayman Brac", "Grand Cayman", "Little Cayman"],

  Comoros: ["Anjouan", "Grande Comore", "Mohéli"],

  "Cook Islands": ["Cook Islands"],

  Croatia: [
    "Brač",
    "Cres",
    "Hvar",
    "Korčula",
    "Krk",
    "Lošinj",
    "Mljet",
    "Pag",
    "Rab",
    "Vis",
    "Šolta",
  ],

  Cuba: ["Cuba", "Isla de la Juventud"],

  Curaçao: ["Curaçao"],

  Dominica: ["Dominica"],

  "Dominican Republic": [
    "Azua",
    "Bahoruco",
    "Barahona",
    "Dajabón",
    "Distrito Nacional",
    "Duarte",
    "El Seibo",
    "Elías Piña",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "María Trinidad Sánchez",
    "Monseñor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samaná",
    "San Cristóbal",
    "San José de Ocoa",
    "San Juan",
    "San Pedro de Macorís",
    "Santiago",
    "Santiago Rodríguez",
    "Santo Domingo Este",
    "Santo Domingo Norte",
    "Santo Domingo Oeste",
    "Sánchez Ramírez",
    "Valverde",
  ],

  Ecuador: [
    "Puerto Ayora",
    "Puerto Baquerizo Moreno",
    "San Cristóbal",
    "Santa Cruz",
  ],

  Fiji: ["Fiji", "Mamanuca Islands", "Yasawa Islands"],

  "France (Mayotte)": ["Petite-Terre"],

  Greenland: ["Greenland", "Qeqertarsuaq"],

  Grenada: ["Carriacou", "Grenada"],

  "Guadeloupe (France)": ["Basse-Terre"],

  Haiti: [
    "Artibonite",
    "Grand'Anse",
    "Hispaniola",
    "La Gonâve Island",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est",
  ],

  Honduras: [
    "Atlántida",
    "Bay Islands",
    "Choluteca",
    "Colón",
    "Comayagua",
    "Cortés",
    "Francisco Morazán",
    "Honduras",
    "Roatán",
    "Utila",
  ],

  Iceland: ["Grimsey", "Iceland"],

  Jamaica: ["Jamaica"],

  Kiribati: ["Tarawa"],

  Madagascar: [
    "Ambodifotatra",
    "Hell-Ville",
    "Madagascar",
    "Nosy Be",
    "Île Sainte-Marie",
  ],

  Maldives: [
    "Addu Atoll",
    "Addu City",
    "Baa Atoll",
    "Dhihdhoo",
    "Eydhafushi",
    "Fonadhoo",
    "Fuvahmulah",
    "Kudahuvadhoo",
    "Kulhudhuffushi",
    "Laamu Atoll",
    "Mahibadhoo",
    "Malé",
    "Manadhoo",
    "Muli",
    "Naifaru",
    "Nilandhoo",
    "Rasdhoo",
    "Thinadhoo",
    "Thulusdhoo",
    "Villingili",
  ],

  "Marshall Islands": ["Marshall Islands"],

  "Martinique (France)": ["Martinique"],

  Mauritius: ["Mauritius Island", "Port Louis"],

  Micronesia: ["Mocronesia"],

  Montenegro: ["Montenegro"],

  Montserrat: ["Montserrat"],

  Mozambique: [
    "Bazaruto Island",
    "Benguerra Island",
    "Ibo Island",
    "Ibo Town",
    "Ilha de Moçambique",
    "Ilha dos Portugueses",
    "Inhaca Island",
    "Magaruque Island",
    "Matemo Island",
    "Medjumbe Island",
    "Quirimba Island",
    "Quirimbas Islands",
    "Santa Carolina Island",
  ],

  Nauru: ["Nauru Island"],

  "Netherlands Antilles": [
    "Saba",
    "Saint Martin (FR)",
    "Sint Eustatius",
    "Sint Maarten",
  ],

  "New Caledonia (France)": ["Grande Terre"],

  Palau: ["Babeldaob", "Koror", "Melekeok", "Rock Islands"],

  Panama: [
    "Isla Bastimentos",
    "Isla Carenero",
    "Isla Colón",
    "Isla Colón (Bocas del Toro)",
    "Isla Contadora",
    "Isla Cébaco",
    "Isla del Rey",
    "Isla Narganá",
    "Isla Popa",
    "Isla Saboga",
    "Isla San José",
    "Isla Solarte",
    "Isla Taboga",
    "Isla Tigre",
    "Isla Ustupu",
  ],

  "Puerto Rico": ["Puerto Rico"],

  Russia: ["Belushya Guba", "Yuzhno-Sakhalinsk"],

  "Réunion (France)": ["Réunion"],

  "Saint Barthélemy (France)": ["Saint Barthélemy"],

  "Saint Kitts and Nevis": ["Nevis", "Saint Kitts"],

  "Saint Lucia": ["Saint Lucia"],

  "Saint Vincent and Grenadines": ["Bequia", "Saint Vincent", "Union Island"],

  Samoa: ["Upolu"],

  Seychelles: ["Baie Sainte Anne", "Mahé", "Praslin", "Victoria"],

  "Solomon Islands": ["Guadalcanal"],

  "São Tomé & Príncipe": [
    "Príncipe",
    "Santo António",
    "São Tomé",
    "São Tomé City",
  ],

  Taiwan: ["Penghu Islands", "Taiwan"],

  Tanzania: [
    "Chake-Chake",
    "Pemba",
    "Stone Town",
    "Unguja",
    "Unguja (Zanzibar)",
    "Uzi Island",
  ],

  Tonga: ["Tongatapu"],

  "Trinidad and Tobago": ["Tobago", "Trinidad"],

  "Turks and Caicos": [
    "East Caicos",
    "Grand Turk",
    "North Caicos",
    "Parrot Cay",
    "Providenciales",
    "Salt Cay",
    "South Caicos",
  ],

  Tuvalu: ["Funafuti"],

  "UK Overseas Territory": [
    "Ascension Island",
    "Saint Helena",
    "Tristan da Cunha",
  ],

  "United States (USVI)": [
    "St. Croix",
    "St. John",
    "St. Thomas",
    "Water Island",
  ],

  Vanuatu: ["Efate"],

  Venezuela: ["Coche Island", "Cubagua Island", "Isla Margarita"],

  Yemen: ["Socotra"],
};

export const getStates = (country?: string) =>
  (country && STATES_BY_COUNTRY[country]) || [];
