# syntax=docker/dockerfile:1

############################
# 1) Dependencies layer
############################
FROM node:20-alpine AS deps
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache libc6-compat

# Copy minimal files to install dependencies with cache
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./

# Install using the detected lockfile
RUN \
  if [ -f package-lock.json ]; then npm ci --include=dev; \
  elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \
  else npm install; fi


############################
# 2) Build layer
############################
FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLE=1

# Bring node_modules and source
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Provide production env for Next build (Firebase public keys, etc.)
# Copy will succeed only if the file exists (we allow it via .dockerignore).
COPY .env.production .env.production

# Use standalone output for a smaller runtime image
# (Make sure next.config.(js|ts) has:  output: 'standalone' )
RUN npm run build


############################
# 3) Runtime layer
############################
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLE=1

# Non-root user
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

# Copy the standalone server and static assets
# These paths are produced when `output: 'standalone'` is enabled.
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Optional: prune dev deps when npm is used (harmless if no package-lock)
RUN [ -f package-lock.json ] && npm prune --omit=dev || true

EXPOSE 3000

# Simple healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"

USER nextjs
# `server.js` is generated by Next standalone output
CMD ["node", "server.js"]
